### ISSUE TITLE
0.2.0 no work on Samsung S22u

### ISSUE THREAD

**Issue by 7tattoo** [AndroidAudioMods/ViPER4Android#10]
0.2.0 can,t no work on SΛMSUNG Galaxy S22 Ultra.But 0.1.0 work fine.
![GIF-230110_171423](https://user-images.githubusercontent.com/122350933/211510655-7e7bc5aa-637b-4702-935d-7b89c465fdd2.gif)

**Comment by Iscle** [comment]
Hi! Try it with v0.3.0 and the latest version of Audio Modification Library. Reopen the issue if it still doesn't work.
