### ISSUE TITLE
(BUG) some function are disabled like convolver, playback gain control .(  driver version 0.6.2 )

### ISSUE THREAD

**Issue by Ch0udhary2** [AndroidAudioMods/ViPER4Android#104]
![WhatsApp Image 2024-09-08 at 10 45 09_630a600a](https://github.com/user-attachments/assets/b8944cc8-039d-4367-a707-9955e35d26e0)

**Comment by peke198822** [comment]
Hi, the same thing happens to me, if you can give me a solution, please.

**Comment by iscle** [comment]
This is known, it's disabled because the features have not been reverse engineered yet.

**Comment by peke198822** [comment]
> Esto se sabe, está deshabilitado porque las funciones aún no han sido sometidas a ingeniería inversa.

Okay, thank you very much for the prompt reply.
