### ISSUE TITLE
Not working on AOSP13 Redmi K30 5G

### ISSUE THREAD

**Issue by takecmd** [AndroidAudioMods/ViPER4Android#12]
I have both tried v0.1.0 and 0.2.0. Neither of them doesn't work
![Screenshot_20230113-084841_ViPER4Android](https://user-images.githubusercontent.com/52288096/212211795-256165fe-bb9c-4b5f-b127-05231dd37a51.png)

**Comment by momo54181** [comment]
打开 传统模式

**Comment by Iscle** [comment]
Hi, make sure you're actually playing audio, and that your app does not require legacy mode to be enabled. In case it does not work, enable legacy mode.
