### ISSUE TITLE
Audio stutter when playing videos online with legacy mode ON

### ISSUE THREAD

**Issue by WhelzC24** [AndroidAudioMods/ViPER4Android#14]
My Device: Oppo A16 (CPH2269)
Android Version: 11
ROM: ColorOS (stock rom)

My Issue:
when I turn on legacy mode then play an online video (ex. YouTube) the audio starts stuttering randomly, audio in music player doesn't stutter

**Comment by Iscle** [comment]
Hi,

this is not a ViPER issue, it might be due to your rom/kernel being too strict with background apps or audio flinger. We can't do anything about it.

Regards

**Comment by WhelzC24** [comment]
I was expecting a solution, but thank you anyway. Now I know that it's not a ViPER issue.
