### ISSUE TITLE
Audio from other apps not cutting in when needed

### ISSUE THREAD

**Issue by megagigawatt** [AndroidAudioMods/ViPER4Android#16]
So I actually had this issue with the original viper4android and the 2.7.

When I am driving and listening to music with spotify or books with audible, the audio from the gps I am using be it Waze, Google Maps, Maps.me tries to cut in and give the directions but there is no audio, it just lowers the music as if the audio tries to cut in and then brings the music back to normal, don't hear any directions from the gps apps.

I spent ages trying to resolve it previously and the only thing that allowed it to work in the end was when I downloaded a modded version of Viper4Android by Shadowstep from here https://forum.xda-developers.com/t/app-all-root-solutions-6-0-viper4android-fx-2-7.3774651/post-87917837

I have this issue with both the 0.1 and 0.2 release, 0.2.0 also crashes randomly on Pixel 7 Pro

**Comment by Iscle** [comment]
Hi!

I had this issue too, I had no idea it was because of ViPER to be honest. Does it also happen with WhatsApp voice notes?

I'll look into it, thanks for pointing it out!

**Comment by megagigawatt** [comment]
> 

I haven't tested with whatsapp audio, but will do when I am heading into work tomorrow and have the gps and spotify all running as well

**Comment by Iscle** [comment]
Hey!

Thanks again for pointing this out, while investigating it it turned out to be a serious implementation bug! It was tricky to find, due to the practically non-existant documentation of the audio effects API, but I eventually got there :)

Will be fixed in the next release.

Regards,
Iscle

**Comment by megagigawatt** [comment]
> Hey!
> 
> Thanks again for pointing this out, while investigating it it turned out to be a serious implementation bug! It was tricky to find, due to the practically non-existant documentation of the audio effects API, but I eventually got there :)
> 
> Will be fixed in the next release.
> 
> Regards, Iscle

Amazing, looking forward to the next update, using 0.1.0 at the moment and just turn viper off when I need to hear directions and listen to music
