### ISSUE TITLE
DDC, CONVOLER, REVERB etc missing 

### ISSUE THREAD

**Issue by Nirvana6969** [AndroidAudioMods/ViPER4Android#19]
Hey dev I noticed DDC, convoler, reverb etc are disabled?
Let me know 
Wired earphone also have no option for enabling those mentioned features.

**Comment by taylorc1009** [comment]
@Nirvana6969 they're not complete yet: https://github.com/AndroidAudioMods/ViPERFX_RE/issues/2

The team developing this project is reverse-engineering the original V4A drivers, so we'll need to be patient while they do their incredible work

**Comment by Iscle** [comment]
As @taylorc1009, it's not ready yet, we don't consider this an issue, thus I'll close it. Thanks!
