### ISSUE TITLE
Output gain distorted 

### ISSUE THREAD

**Issue by Pdaddy29** [AndroidAudioMods/ViPER4Android#2]
So far most of the parts I use are working.
The Master Limiter>output gain doesn't like being above 0.0. 
It gets distorted. Overall its headed in the right direction though. 
Pixel 7 Pro
![Screenshot_20230102-031815](https://user-images.githubusercontent.com/30885817/210212950-e6044883-081c-408d-9613-fd3635d5370c.png)

**Comment by Iscle** [comment]
It was because of the missing Threshold limit. Fixed in v0.2.0.
