### ISSUE TITLE
Will not work with Sony Xperia 10 Plus

### ISSUE THREAD

**Issue by Candlemass** [AndroidAudioMods/ViPER4Android#21]
I followed the install directions exactly as stated, flashed the zip with magisk then installed the apk before rebooting. 0.1 automatically crashes as soon as you attempt to start the app. 0.2 will open but always complains about drivers not being installed while providing a link to this github page.

**Comment by Candlemass** [comment]
Anybody home?

**Comment by Iscle** [comment]
Hi! Try it with v0.3.0 and the latest version of Audio Modification Library. Reopen the issue if it still doesn't work.

**Comment by Candlemass** [comment]
@Iscle

The "no driver found" issue still persists with 0.3. I don't get the error if I don't install Audio Modification Library however the app doesn't do anything under that situation though.
