### ISSUE TITLE
Driver not installing?

### ISSUE THREAD

**Issue by CatFishing4Guyz** [AndroidAudioMods/ViPER4Android#24]
I don't seem to be the only one, lots of people in the Telegram channel with the same issue. Same with normal V4A, repackaged, and this one. Tried using the 0.1.0 driver with the 0.2.0 app but still didn't fix the driver issue. Samsung A22 5G, Android 13.

**Comment by Iscle** [comment]
Hi! Try it with v0.3.0 and the latest version of Audio Modification Library. Reopen the issue if it still doesn't work.

**Comment by ghost** [comment]
> Hi! Try it with v0.3.0 and the latest version of Audio Modification Library. Reopen the issue if it still doesn't work.

I already fixed my problem. Normal Viper and the reverse engineered one works again, turns out a setting on my GSI was the issue. Thanks
