### ISSUE TITLE
Driver not found... Samsung galaxy s20fe

### ISSUE THREAD

**Issue by kodein1** [AndroidAudioMods/ViPER4Android#26]

**Comment by AnaxMorden** [comment]
Updated APP?
First installed AML and then installed V4A?
Installing V4A can cause issues

**Comment by kodein1** [comment]
Yes. First aml, instal v4a app, flash magisk module

**Comment by AnaxMorden** [comment]
> Yes. First aml, instal v4a app, flash magisk module

Have you rebooted between these steps to activate AML correctly?

**Comment by kodein1** [comment]
yes

**Comment by kodein1** [comment]
I'll try turning off the sound mods. (ainur narsil....)

**Comment by AnaxMorden** [comment]
Yes, if that doesnt work, disable them manually

**Comment by kodein1** [comment]
After uninstall audio mod v4a work

**Comment by AnaxMorden** [comment]
Perfect then Please close the issue
