### ISSUE TITLE
Driver v0.3 not enabled on bluetooth devices.

### ISSUE THREAD

**Issue by phyrz91** [AndroidAudioMods/ViPER4Android#27]
Hi, thanks for your hard work!

I have a problem with the v0.3 driver, it is enabled and processed on speakers in Xiaomi. However, when I connect bt headphones and play music, the status of processing and enabled is no. I tried driver v0.1 but it doesn't work at all on my phone.

Playing music on the built-in speakers, everything works.

[![Screenshot_20230311-214848_Trebuchet.th.png](https://tinypic.host/images/2023/03/11/Screenshot_20230311-214848_Trebuchet.th.png)](https://tinypic.host/i/rUtnS)

After connecting bt headphones.

[![Screenshot_20230311-214709_Trebuchet.th.png](https://tinypic.host/images/2023/03/11/Screenshot_20230311-214709_Trebuchet.th.png)](https://tinypic.host/i/rUs9b)

After playing music through bt headphones.

[![Screenshot_20230311-214606_Trebuchet.th.png](https://tinypic.host/images/2023/03/11/Screenshot_20230311-214606_Trebuchet.th.png)](https://tinypic.host/i/rUDEu)

I've Xiaomi 12 with LOS 20.

**Comment by Anax-M** [comment]
https://github.com/AndroidAudioMods/ViPER4Android/issues/15#issue-1549317863

Some Codecs are currently broken, go into Developer Settings and try to set Bluetooth Codecs to SBC while connected to the Bluetooth device

**Comment by BesoC** [comment]
Still does not work when connected to headphones, doesn't matter whether codec is set to SBC or aptX.
OnePlus 11, OOS10, Android 13, Magisk 26.1.

**Comment by devnoname120** [comment]
@phyrz91 Could you reupload your images? The links are broken. Note that you don't need an external host, you can directly drag & drop images in the textbox when you are editing your comment.

**Comment by iscle** [comment]
Hi, this issue should be fixed starting from v0.4.0. If not, reopen the issue with a screenshot of the driver status on the latest version (v0.5.0 at the time of writing).
