### ISSUE TITLE
Separate profiles and options for speakers, headphones, bluetooth

### ISSUE THREAD

**Issue by ghost** [AndroidAudioMods/ViPER4Android#29]
Just like normal V4A. Options for each of the different output methods. For example, I want speaker optimization for speakers, but I don't want my headphones sounding terrible.

**Comment by iscle** [comment]
The app already chooses the appropriate profile based on the connected device.

All options are available for all devices, but if you won't want one (eg. Speaker optimization) with your headphones, don't enable it.
