### ISSUE TITLE
Will not work with Sony Xperia 10 Plus

### ISSUE THREAD

**Issue by Candlemass** [AndroidAudioMods/ViPER4Android#32]
@Iscle

The "no driver found" issue still persists with 0.3. I don't get the error if I don't install Audio Modification Library however the module doesn't do anything under that situation though.

_Originally posted by @Candlemass in https://github.com/AndroidAudioMods/ViPER4Android/issues/21#issuecomment-1480204828_

**Comment by Iscle** [comment]
Hi,

If you don't get the error when not installing AML it means ViPER is working correctly. If it is not processing even with Legacy Mode, then it's an issue with the app you're using.

Regards,
Iscle

**Comment by Candlemass** [comment]
@Iscle

Yes, but I already have Ainur Narsil MKI installed so do I not need Audio Modification Library to have both modules fuctioning correctly at the same time?

What "app" are you referring to?

**Comment by Candlemass** [comment]
????

**Comment by Candlemass** [comment]
Well this looks like a lost cause....

**Comment by Candlemass** [comment]
This is not "completed". You never answered ny followup question which is critical.

**Comment by Iscle** [comment]
> This is not "completed". You never answered my followup question which is critical.
> 
> "@Iscle
> 
> Yes but I already have Ainur Narsil MKI installed so do I not need Audio Modification Library to have both modules fuctioning correctly at the same time?
> 
> What "app" are you referring to? The viper.apk downloaded from this repository?"

As I said before, If you don't get the error when not installing AML it means ViPER is working correctly.

**Comment by Candlemass** [comment]
> > This is not "completed". You never answered my followup question which is critical.
> > "@Iscle
> > Yes but I already have Ainur Narsil MKI installed so do I not need Audio Modification Library to have both modules fuctioning correctly at the same time?
> > What "app" are you referring to? The viper.apk downloaded from this repository?"
> 
> As I said before, If you don't get the error when not installing AML it means ViPER is working correctly.

@Iscle

As I said before, it will still not install with audio modification library which you yourself stated is needed with mutiple audiio modules. Not sure why you keep skipping over this when it's been made clear from the the start...

**Comment by Iscle** [comment]
AML is only needed **IF** the error pops up. If not, it is not needed.
