### ISSUE TITLE
Driver does not attempt to install, shows 'unknown' 

### ISSUE THREAD

**Issue by Matakor** [AndroidAudioMods/ViPER4Android#34]
ROG Phone 6D Ultimate
Magisk v 26100
Audio compatibility patch v2.5 installed
Audio modification library v4.2 installed

Latest versions I can find of each. Not sure why, but driver does not attempt to install? And does not state that driver can't be found. Turning on kills all audio. 

![Screenshot_20230412-173749_ViPER4Android](https://user-images.githubusercontent.com/6760522/231591698-d1b20eeb-60aa-4a34-83ae-7570ed1bb29d.jpg)
![Screenshot_20230412-182349](https://user-images.githubusercontent.com/6760522/231599318-49aedbeb-8b3c-4d6a-9a88-3f14ee127de1.jpg)

**Comment by iscle** [comment]
The driver has been installed fine. Enable it "Master Limiter" and play music in order to see the status dialog information.

**Comment by Matakor** [comment]
As stated in the final line, this kills all audio. In other words, you can't hear anything.

**Comment by Matakor** [comment]
ok, scratch that.

Audio does indeed play. Oddly, with only speaker, legacy mode wasn't needed. With my bluetooth, it doesn't work. Without legacy, it does make not sound. With, it does, but is not processing. probably LDAC, would be my guess

Edit: tinkered with bluetooth settings, it seems to be working now, but I'm no longer on LDAC. Sad. Anyhow, thanks for at least making my dumb self look at it again lol
