### ISSUE TITLE
Add a method to install without Magisk

### ISSUE THREAD

**Issue by putraadr** [AndroidAudioMods/ViPER4Android#35]
I have Samsung A105G with LineageOS 20 (Android 13) 
Rooted with KernelSU.
When I install v4afx.apk the app asks for Driver which naturally I pressed YES. 
but it fails and says "cannot remount /system rw" 

the ZIP you provided is for magisk. is there any other way to install (or install manually?)

**Comment by worstperson** [comment]
Doesn't KernelSU support Magisk modules, at least experimentally?

That error says your system is read-only thus it's not possible to install libraries and configuration unless you use a module to overlay those files or modify your super.img to make partitions R/W. It's also possible to dump a super partition and rebuild it with partitions that have your desired modifications with a good bit of effort.

**Comment by iscle** [comment]
Hi, you might be using another version. This version does not ask for driver installation when the app is opened (it only informs about the driver not being present)
