### ISSUE TITLE
Bug preset for output devices on version 0.4.0

### ISSUE THREAD

**Issue by Clourynth** [AndroidAudioMods/ViPER4Android#38]
There is a bug in the latest version, when changing the output device from the internal speakers to the headphones, it does not automatically change the output preset. In the previous version 0.3.0 just work fine.

![Screenshot_20230518-134230_Kiwi_Browser](https://github.com/AndroidAudioMods/ViPER4Android/assets/83362616/e2a79f9d-9e39-49b2-aa03-48e2b279b2c0)
![Screenshot_20230518-134236_Kiwi_Browser](https://github.com/AndroidAudioMods/ViPER4Android/assets/83362616/99e59bc6-e575-4663-a1a0-086bf8a9e710)

**Comment by iscle** [comment]
Will check, thanks for the feedback!

**Comment by iscle** [comment]
Check the latest update.

**Comment by bgmiroadmi-source** [comment]
Ha mujhe chalu karna hais

**Comment by bgmiroadmi-source** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/a92acaa4-ef68-4bc8-9bb7-6eb5d758ba96" />
