### ISSUE TITLE
Fiio m6

### ISSUE THREAD

**Issue by Pecinski** [AndroidAudioMods/ViPER4Android#41]
I have a fiio m6 works on android 7, I install the driver and everything is ok, but the application prompts me to install, but it is actually installed

**Comment by iscle** [comment]
Any logs, screenshots...?

**Comment by Pecinski** [comment]
![IMG_20230522_185543_945](https://github.com/AndroidAudioMods/ViPER4Android/assets/134307658/63af1064-bcbc-43f0-9f45-68005df04412)

**Comment by Pecinski** [comment]
![IMG_20230522_185544_015](https://github.com/AndroidAudioMods/ViPER4Android/assets/134307658/daa5111a-5cbe-4ae7-9e1f-8a98ca3b46dd)

**Comment by iscle** [comment]
3 main issues:

1. You're not using the latest version.
2. You're using a modified app (not downloaded from here = not supported by us).
3. You have an older version also installed.

**Comment by Pecinski** [comment]
I removed the old version and it's the same again

**Comment by iscle** [comment]
Did you update to the latest version and use the official app?

**Comment by Pecinski** [comment]
Yes my versio magisk 22.1

**Comment by iscle** [comment]
Update ViPER to the last version available in this repository and reopen the issue if the error persists.

**Comment by Pecinski** [comment]
![IMG_20230522_201919](https://github.com/AndroidAudioMods/ViPER4Android/assets/134307658/8e40dc98-085b-457c-ac60-a5cf3cf18a09)
![IMG_20230522_201847](https://github.com/AndroidAudioMods/ViPER4Android/assets/134307658/21ead8fe-9f2d-4cfd-a15b-616556f59d57)
![Uploading IMG_20230522_201542.jpg…]()

**Comment by Pecinski** [comment]
![IMG_20230522_201542](https://github.com/AndroidAudioMods/ViPER4Android/assets/134307658/ed2aebe1-c7c5-4979-b0ec-ae015d14e29e)

**Comment by iscle** [comment]
Now it's better. Try installing the latest version of AML and see if that fixes the issue...

**Comment by Pecinski** [comment]
what is aml 😁

**Comment by Pecinski** [comment]
Audio modification library?

**Comment by Pecinski** [comment]
![Uploading IMG_20230522_202837.jpg…]()
