### ISSUE TITLE
Works with YouTube ReVanced only in legacy mode

### ISSUE THREAD

**Issue by BesoC** [AndroidAudioMods/ViPER4Android#43]
I'm sure it's a minor issue, but still....
While processing sound from Spotify in both legacy and non-legacy modes, audio from YouTube ReVanced is being processed only with legacy mode on. Legacy mode off results in drive status - VIPER is not initialized.

**Comment by iscle** [comment]
Hi,

This is not an issue with ViPER and cannot be fixed by us. It has to be fixed by the app developer.
