### ISSUE TITLE
Viper not working with Bluetooth (7.1.4 dolby conflict?)

### ISSUE THREAD

**Issue by Redvex67** [AndroidAudioMods/ViPER4Android#45]
Hello,
Xiaomi 13 android 13 xiaomi.eu stable rooted with kernelsu. Player Is poweramp
No problem with phone speaker doesn't work via bluetooth.
Legacy mode disabled audio stop working
![Disabled](https://github.com/AndroidAudioMods/ViPER4Android/assets/135276082/69c627de-d5e1-42d2-9ea8-8b1284825c78)

Legacy mode enabled everything is ok except the fact that is not processing
![Enabled](https://github.com/AndroidAudioMods/ViPER4Android/assets/135276082/7b26dfc8-f486-48b9-bb72-7e846a821269)

Let me know if you need logs or whatever!
Best Regards!
Claudio

**Comment by iscle** [comment]
If anyone is here for the same issue, the solution is to disable all MIUI dolby effects.
