### ISSUE TITLE
Disable notification if master switch is disabled

### ISSUE THREAD

**Issue by ghost** [AndroidAudioMods/ViPER4Android#47]
The notification is always active, if music is playing. Even when the master switch is disabled. This consumes more battery. So only show the notification if master switch is enabled and music is playing for best battery management.

**Comment by iscle** [comment]
Hi,

The notification does not consume any battery, it's just a notification, the service is not doing anything.

Changing the logic of service startup is hard at this point, so it will remain like this at least until the release version is finished.
