### ISSUE TITLE
Use MaterialYou 3.0

### ISSUE THREAD

**Issue by ghost** [AndroidAudioMods/ViPER4Android#48]
To make the app more user friendly and to align it with the android materialyou ecosystem, use materialyou 3.0. This adds the feature to customize the appearance of the app.

**Comment by DeanR97** [comment]
there is an alternative App, which uses Material You

https://github.com/WSTxda/ViperFX-RE-Releases

**Comment by iscle** [comment]
Hi, the app's UI will not be updated until the project gets out of alpha version. I'm closing the issue for now.
