### ISSUE TITLE
Viper refuses to process certain codecs

### ISSUE THREAD

**Issue by Dialgatrainer02** [AndroidAudioMods/ViPER4Android#5]
Aptx,aptx HD and ldac don't have any effects applied to them as and SBC work fine usb also isn't processed

**Comment by iscle** [comment]
Hi, this issue should be fixed starting from v0.4.0. If not, reopen the issue with a screenshot of the driver status on the latest version (v0.5.0 at the time of writing).

**Comment by Dialgatrainer02** [comment]
![Screenshot_20231122-193133](https://github.com/AndroidAudioMods/ViPER4Android/assets/96637854/67313d98-ad5e-43fb-841a-e045416fc602)
Fiio btr5 using ldac codec source is 44.1k 16bit from tidal over Bluetooth isn't applying what other logs can I get?

**Comment by Dialgatrainer02** [comment]
@Iscle I can't reopen as you closed it

**Comment by iscle** [comment]
By the looks of it, android is not calling the process function, so it's not something we can fix, at least at first glance. I will try to find some more information.

**Comment by Dialgatrainer02** [comment]
I tried to edit the eq through fiio control and it gave me an error about being unable to as it's ldac is android protecting it from being processed and is there a way to hook and process it anyway?
