### ISSUE TITLE
Android Auto 

### ISSUE THREAD

**Issue by Moassie** [AndroidAudioMods/ViPER4Android#52]
Im using latest Version on Xiaomi 12s. Its working good with legacy on speaker and Bluetooth. 
The Problem is Android Auto, its working when its with cable connected but not working when without cable (Connection with WiFi, audio still Bluetooth). 

I dont understand why its working wired und Not working Wireless

**Comment by iscle** [comment]
It must be an issue with legacy mode. I don't use legacy mode and it works just fine for me on wireless AA.

**Comment by seffparker** [comment]
I can confirm this. 

This thread helped to solve the issue. I have been using Legacy Mode until noticed V4A not working with AA-WIRELESS. Then I tried find out why default mode (non-legacy) doesn't works for me. As far as I understand, in legacy mode, the effect applies at device's audio output stream, but in default mode, effect applies at app's output stream. 

For my case, it was my app (PowerAmp) which doesn't broadcast the audio session id, so V4A could not process in default mode. More details here https://pittvandewitt.github.io/Wavelet/Settings/#legacy-mode

**Comment by iscle** [comment]
> For my case, it was my app (PowerAmp) which doesn't broadcast the audio session id, so V4A could not process in default mode. More details here https://pittvandewitt.github.io/Wavelet/Settings/#legacy-mode

PowerAmp can broadcast it but only if you enable it in the app's settings. I'm not sure why they did it like this TBH. Glad you fixed it!
