### ISSUE TITLE
Not processing in games

### ISSUE THREAD

**Issue by Bonsoir98** [AndroidAudioMods/ViPER4Android#55]
The driver works properly in apps like Spotify, YouTube, music players or social media, it doesn't seam to work in games.

**Comment by iscle** [comment]
This is not a ViPER issue, enable legacy mode and see if it works.

**Comment by Bonsoir98** [comment]
The legacy setting is enabled

**Comment by iscle** [comment]
We can't do anything about it, it's an Android issue.
