### ISSUE TITLE
Limited functionality until manually connecting/disconnecting bluetooth audio device

### ISSUE THREAD

**Issue by doingthedoings** [AndroidAudioMods/ViPER4Android#57]
My problem is a bit odd, as is the work-around I've managed to come up with.

I'm running this on a raspberry pi 4 on lineageos20 with hifiberry dac support, and it works great until I try and get v4a functionality to work properly. v4a seems to treat the hifiberry dac as an internal speaker(of which there is none), and as a result I have limited functionality with many features missing from the list(as would be typical for a phone or tablet that isn't connected to headphones or a bluetooth audio device).

I figured out that by launching v4a and then connecting an aux-to-bluetooth adapter module, and then immediately turning off bluetooth, v4a will recognize the device changed and gives me all of the features for the bluetooth device. When I disconnect the bluetooth module, v4a then falls back to processing/output through the dac, and I retain all expected v4a functionality.

My current semi-permanent workaround is to launch v4a at boot up via tasker, then enable bluetooth, wait 5 seconds, then disable bluetooth to do the audio device switch-over, and then go back to the home screen where everything works from then on as I would expect.

I've tried editing the audio_policy config files in /vendor/etc/ to try and manually set my default device as "Wired Headphone" or "Wired Headset" but neither of those will give me any v4a functions at all, I just see a blank screen until I do the bluetooth trick. 

Is there a way to add full v4a functionality to the default "speaker" device to enable functionality for odd cases like this?

**Comment by iscle** [comment]
Hi, by the issue you're describing it looks like you're not using this version of ViPER4Android, but an older version. This version has all features enabled by default in any output device.

Regards,
Iscle
