### ISSUE TITLE
[Feature Req] All Audio Settings for Speaker

### ISSUE THREAD

**Issue by jasonmerc** [AndroidAudioMods/ViPER4Android#61]
I'm requesting a feature to enable the full range of audio settings for the Speaker (viper bass, viper treble, DDC, and all that other stuff that's only in Headphones and Bluetooth).

Normally in Viper, the Speaker settings are limited, which might make sense in normal cases because most of those settings wouldn't make much difference on a tiny phone speaker anyway.  However, I have Viper on an Android head unit in my car, and it's stuck on the limited Speaker settings. Having access to the full range of settings in this case would be awesome since we're talking surround sound car speakers, not some tiny phone speaker.

This doesn't mean that the full settings have to be available by default, it could even be something you'd have to manually enable in settings somewhere.  Again, if there was just some way to do this so I can get the full Viper experience on my car's head unit, that would rock.

**Comment by iscle** [comment]
Hi, this is already available in this ViPER version ;)

**Comment by jasonmerc** [comment]
> Hi, this is already available in this ViPER version ;)

Could you tell me how to access this feature?  I can't find anything regarding it in the Settings menu.

EDIT: I just realized too, I think I flashed the Viper4AndroidRepackaged module on my head unit by mistake... I don't know if that makes a difference, but either way I couldn't see this option anywhere in the Settings menu.

**Comment by iscle** [comment]
It's enabled by default! Make sure you're not using another version if you don't see all settings.

**Comment by jasonmerc** [comment]
I just realized the error in my ways, this is a further modded version of Viper, not the main branch that others pull from.

Well, thank you again.  Flashed this on my car's head unit and I'm gonna see how it works.  Looking forward to new releases when more stuff gets working :)
