### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by AlphaCraft9658** [AndroidAudioMods/ViPER4Android#68]
Just a quick question I have is whether this project is still active. The las alpha release is 6 months old and the last commit on the reverse engineering repository has been 2 months ago. Just want an update for whether this is still being worked on. It's a great project!

**Comment by iscle** [comment]
It will be worked on when/if we don't have other, higher priority, projects.

So far the project works in most devices, and it fits my needs, so I don't have any reason to prioritize it over my other projects. Other maintainers might share the same thoughts as me :)

It is an open source project, so PRs are always welcome ^^
