### ISSUE TITLE
Viper4Android 0.5.0 app keeps crashing on startup

### ISSUE THREAD

**Issue by UberNorse** [AndroidAudioMods/ViPER4Android#69]
Hello,

I am having the app crash on my wife's phone upon startup on a Pixel 7a with Android 14 and Magisk 26.4. App has been previously working fine for a long time so unsure of the issue here. I have uninstalled app, cleared data, rebooted, re-flashed module, reinstalled app, and everything else I can think of. 
Attached is logcat. 

Please advise if you need anything else from me hopefully I have included everything and this isn't something I have overlooked, thank you for your work on this project and this issue.

[v4alog.txt](https://github.com/AndroidAudioMods/ViPER4Android/files/13541672/v4alog.txt)

**Comment by UltraHQ** [comment]
Not sure if it's related, but I'm having the same issue on 0.6.0

The app for 0.5.0 works fine though

**Comment by UberNorse** [comment]
> Not sure if it's related, but I'm having the same issue on 0.6.0
> 
> The app for 0.5.0 works fine though

I just updated my phone (not the problem phone) to 0.6.0 and experienced the crash as well. Downgrade to 0.5.0 has me back up and running though.

**Comment by pdasilem** [comment]
> Not sure if it's related, but I'm having the same issue on 0.6.0

just look at magisk module - my ksu shows version 0.5.0. Maybe it's an issue.

**Comment by bombadier** [comment]
https://github.com/AndroidAudioMods/ViPERFX_RE/commit/07b390247b2c94c8f1dee27be14d599134cf56aa
Shows an updated Version code 20231209 but the downloaded 0.6.0 module still has the 0.5.0 values

**Comment by iscle** [comment]
Please, try with the latest release which is reported working on many A14 devices :)

**Comment by UberNorse** [comment]
Not sure what the issue was as it continued with 0.6.2 but after some cache clearing and reinstallation of module and app we are now functioning. Thank you. Issue closed.

**Comment by UberNorse** [comment]
Closed.
