### ISSUE TITLE
No support 0.2.0

### ISSUE THREAD

**Issue by luckylukz02** [AndroidAudioMods/ViPER4Android#7]
Was having this issue on 0.1.0 #4 

Could get it to work with the legacy toggle:

![Screenshot_20230108-170157_ViPER4Android](https://user-images.githubusercontent.com/80491975/211209585-bb3db5e3-ead9-4d95-8ee3-52cf375374a9.jpg)
![Screenshot_20230108-170218_ViPER4Android](https://user-images.githubusercontent.com/80491975/211209586-4e96cbd0-0b8a-4b28-a336-85eb04de328e.jpg)

Since 0.2.0 cannot get it to work:

![Screenshot_20230108-170904_ViPER4Android](https://user-images.githubusercontent.com/80491975/211209627-6565bb51-cd0d-4362-b807-828c50bdc6fe.jpg)

When playing music:

![Screenshot_20230108-170912_ViPER4Android](https://user-images.githubusercontent.com/80491975/211209640-22160d18-2181-48ca-a465-e033977b0acd.jpg)

**Comment by mar-jac** [comment]
![Screenshot_20230108-132329](https://user-images.githubusercontent.com/55053226/211212563-ccee0f86-5597-44f7-9dae-20cbd65415ec.png)

Same issue - Pixel 7 Pro

**Comment by Iscle** [comment]
Hi! Try it with v0.3.0. Reopen the issue if it still doesn't work.
