### ISSUE TITLE
Not being able to update 

### ISSUE THREAD

**Issue by pxlkeshi** [AndroidAudioMods/ViPER4Android#70]
Idk if it's cus I'm using magisk delta but I did the exam same steps installed both 0.6.0 and the app and then rebooted but magisk still shows the 0.5.0 module and the app keeps crashing removed v4a completely but it keeps installing the 0.5.0 module even tho the file is 0.6.0

**Comment by edgars-cirulis** [comment]
He forgot to rename the label from 0.5.0 to 0.6.0 it's just text nothing to worry about.

**Comment by bombadier** [comment]
I dont think the module has been updated, I just tried to update and 0.6.0 is force closing, downgraded back to 0.5.0 and is working again

**Comment by bombadier** [comment]
Version. 6.1 still FC on android 14

**Comment by iscle** [comment]
Fixed!
