### ISSUE TITLE
Youtube music stays on on normal mode. 

### ISSUE THREAD

**Issue by NBruderman** [AndroidAudioMods/ViPER4Android#72]
While listening to music on spotify, the app opens and closes the process as it should.
However, I noticed that with Youtube Music the notification will stay on, even after pausing, stopping, and even force stopping the youtube music app.
Even after force stopping the viper app, when trying again, it will still stay on.
The only fix I found was to turn legacy mode on and off again.

**Comment by iscle** [comment]
Yes, youtube's fault, we can't do anything about it 😅. They have to fix the audio effect close broadcast.

**Comment by NBruderman** [comment]
This is such a Google thing to do... Thanks for the quick reply!

**Comment by iscle** [comment]
Could probably be fixed with an xposed module, if it's something that's driving you crazy... The only side effect of leaving it open is that it will never release resources (memory, basically). CPU usage shouldn't be affected at all.

**Comment by NBruderman** [comment]
Although I use xposed, I'm not a developer, so I don't know how to code such a thing... However, I don't use YouTube music that often (I use mostly spotify and regular YouTube) so it doesn't bother me that much. It's annoying, but not game-breaking.

________________________________
