### ISSUE TITLE
ViPER4Android-RE v0.6.2 Installs different APK? 

### ISSUE THREAD

**Issue by ohmybahgosh** [AndroidAudioMods/ViPER4Android#74]
I could be a moron, so bare with me.  When installing the latest APK it doesn't update the existing APK, but rather installs a brand new version.  Should we be migrating to the new apk?

**Comment by iscle** [comment]
Hey,

the "new" release is just a release to fix the TAG and also a bug where for some reason github did not show it in the releases section.

It's the same as the old one.

Regards,
Iscle

**Comment by ohmybahgosh** [comment]
For me the latest APK installs a different viper4android..

New APK:
![Screenshot_20231211-152558](https://github.com/AndroidAudioMods/ViPER4Android/assets/77786782/7587491b-aa2a-4401-842d-b889ced75e34)


OLDER APK:
![Screenshot_20231211-152657](https://github.com/AndroidAudioMods/ViPER4Android/assets/77786782/4fe9f865-1686-4394-bf3c-3f04c720a0a8)


Is this the apk we should install?
https://github.com/AndroidAudioMods/ViPER4Android/releases/download/v0.6.2/V4A_App_0.6.2.apk

**Comment by iscle** [comment]
The "old" apk is a modified version of the one published here. We don't give any support for it. As I said, the latest one published by us is v0.6.2. Available in the releases page, as always.

Regards

**Comment by ohmybahgosh** [comment]
That clears it up, thank you!
