### ISSUE TITLE
Is ViPER4Android-RE v0.6.2 the latest APK? 

### ISSUE THREAD

**Issue by ohmybahgosh** [AndroidAudioMods/ViPER4Android#75]
Is this the latest release we should be using?  My other ticket was closed, so I had to make another one.

https://github.com/AndroidAudioMods/ViPER4Android/releases/download/v0.6.2/V4A_App_0.6.2.apk

**Comment by iscle** [comment]
Yes, v0.6.2 is the latest version.

In theory you can still reply to closed issues...
