### ISSUE TITLE
Viper4android Non Root Apk?!

### ISSUE THREAD

**Issue by WhiteDevil9o** [AndroidAudioMods/ViPER4Android#88]
Wouldn't it be bad if you developed or programmed viper4android so that you could use it without root and the driver was already included in the apk?!?

**Comment by iscle** [comment]
Hi, this is not possible on Android.

**Comment by griha41** [comment]
> Hi, this is not possible on Android.

Heh thi is not possible at all no matter of type of the OS, there's no any kind of ViperFX for android without root installation because of installation of itself required root @ the base!

**Comment by J4CKED** [comment]
ViPER4Android FX [Non Root]

Requirements
-- android 10, arm 64
-- custom recovery
-- ViPER4Android rootless zip file
-- ViPER4Android apk

Download https://t.me/modulesrepo
https://t.me/modulesrepo/219
