### ISSUE TITLE
Some options greyed out.

### ISSUE THREAD

**Issue by Mrsalai** [AndroidAudioMods/ViPER4Android#89]
Using latest v4a driver and apk, some options like headphone durround is greyed out, which I really would like to use.
![Screenshot_2024-03-17-12-57-31-834_com aam viper4android](https://github.com/AndroidAudioMods/ViPER4Android/assets/106451720/0b6a06f4-25bf-4503-89d3-9e120eb3ca87)
![Screenshot_2024-03-17-12-57-22-989_com aam viper4android](https://github.com/AndroidAudioMods/ViPER4Android/assets/106451720/db066860-a548-43d2-ba9b-2bc07ccf6478)

**Comment by supaplexer** [comment]
Was about to post the same issue with the same identical screens. I'm on HyperOS, device is garnet (Snapdragon 7s Gen 2). I also have the Audio Modification Library installed and working. I wonder if we have to actually disable/uninstall any other audio app that might be interfering with V4A RE

**Comment by iscle** [comment]
They are greyed out on purpose because the reverse engineering work has not been completed yet. They will be enabled when it's ready :)

**Comment by tw4test** [comment]
Is there any update or other options?

**Comment by DeepBlueBubble** [comment]
Some preset can actually enable those settings. Which is quite annoying because you can't disable back.
