### ISSUE TITLE
Bass mode  change to  pure bass+  or  subwoofer,driver will be no find.

### ISSUE THREAD

**Issue by 7tattoo** [AndroidAudioMods/ViPER4Android#9]
SΛMSUNG Galaxy S22 Ultra.
One UI 5.0 Android 13.
Viper Fx 0.1.0  or 0.2.0
Legacy mode On.

![Screenshot_20230110_163811_ViPER4Android](https://user-images.githubusercontent.com/122350933/211504211-da674962-c899-4413-8c8d-0eaf6aa20759.jpg)
![Screenshot_20230110_163819_ViPER4Android](https://user-images.githubusercontent.com/122350933/211504220-6cd21c9f-a261-484d-958f-578d1ea1e516.jpg)
![Screenshot_20230110_163908_ViPER4Android](https://user-images.githubusercontent.com/122350933/211504224-888f05dd-81db-4569-aa0d-025d0019329e.jpg)

**Comment by Iscle** [comment]
Hi!

Yep, it's a known issue, the driver crashes...

I'll close the issue once it's fixed.

**Comment by Iscle** [comment]
This issue has been fixed in the latest v0.3.0 release.
