### ISSUE TITLE
Uses old algorithm for audio processing through fir equaliser 

### ISSUE THREAD

**Issue by Shubhamkr4** [AndroidAudioMods/ViPER4Android#93]
Equaliser from many audio platforms sounds a lot different on v4a, the reason could be older encoding techniques due to which eqs sound same in different apps like jdsp or dolby but different on v4a.... basically v4a's eq cannot be used anywhere else and any other app's eq cannot with v4a.....plz update the encoding mechanism of v4a eq in the alpha version.....
Tested on v4a alpha(non legacy) as well as v4a repackaged(legacy)

**Comment by iscle** [comment]
Hi,

People using V4A uses it because it is different from every other EQ, and it's easy to use most of the time. The reverse engineering project aims to be as close as possible to the original, so this won't be happening.

Regards,
Iscle

**Comment by Shubhamkr4** [comment]
But its so much complex for new users to get in the ecosystem due to all the different kinds of convolvers and ddc files, which doesn't really make much sense for new comers and in this case if the eqs are updated there will be no need for different kinds of ddc and audio correction files for different equipments, it just makes the process long and unbearable at the same time for users who don't know what those are, plus also for the modern encoding process it defines the correct values automatically so no ddcs will be required if this happens, which will shorten the time period required for setup
Hoping you guys will understand it will not break the essence of the app and will make it more convenient and easy to use.
