### ISSUE TITLE
spotube keeps viper4android driver active after closing app

### ISSUE THREAD

**Issue by Aracnoss** [AndroidAudioMods/ViPER4Android#98]
Unsure why, but spotube keeps the driver active in viper4android even after the app is closed.

![Screenshot_20240515-091832](https://github.com/AndroidAudioMods/ViPER4Android/assets/7039164/ccdc01ba-7b20-45ad-82a9-2c2f8030a4e1)

![Screenshot_20240515-092242](https://github.com/AndroidAudioMods/ViPER4Android/assets/7039164/65cd6151-6b00-4874-82cf-5e6edf885755)

**Comment by iscle** [comment]
This is an issue with the app itself, unfortunately we can't do anything about it. It's better to contact the app developer.
